fix new listen handler initialization
projectdiscovery/naabu pull request #1233
Opened 2024-10-08 10:38 UTC by dogancanbakir

Closes #1125

```console
sudo ./example
[INF] Running SYN scan with root privileges
[INF] syn scan is not possible, falling back to connect scan
[INF] Running SYN scan with root privileges
[INF] Running SYN scan with root privileges
[INF] syn scan is not possible, falling back to connect scan
[INF] Running SYN scan with root privileges
[INF] syn scan is not possible, falling back to connect scan
[INF] syn scan is not possible, falling back to connect scan
[INF] Running SYN scan with root privileges
[INF] Running SYN scan with root privileges
[INF] Running SYN scan with root privileges
[INF] Running SYN scan with root privileges
[INF] syn scan is not possible, falling back to connect scan
[INF] Running SYN scan with root privileges
[INF] Running SYN scan with root privileges
127.0.0.1:5000
[INF] Found 1 ports on host 127.0.0.1 (127.0.0.1)
&{127.0.0.1 127.0.0.1 [5000-0-false] 0}
```

2024-10-11 13:22 UTC, Mzack9999 approved these changes

2024-10-11 13:23 UTC, Mzack9999 requested changes
Implementation: lgtm

Please have a look at failing integration tests

2024-11-08 14:57 UTC, Mzack9999 approved these changes

2024-11-08 18:02 UTC, ehsandeep approved these changes

2024-11-08 18:23 UTC, merged