Add health-check
projectdiscovery/naabu pull request #350
Opened 2022-06-09 09:04 UTC by Mzack9999

## Description
This PR implements health-check functionality

## Example
```console
$ go run . -health-check
Version: 2.0.7
Operative System: darwin
Architecture: arm64
Go Version: go1.18.2
Compiler: gc
Privileged/NET_RAW: Ok
Config file "/Users/user/.config/naabu/config.yaml" Read => Ok
Config file "/Users/user/.config/naabu/config.yaml" Write => Ok
IPv4 connectivity to scanme.sh:80 => Ko (dial tcp4 128.199.158.128:80: connect: connection refused)
IPv6 connectivity to scanme.sh:80 => Ko (dial tcp6 [2400:6180:0:d0::91:1001]:80: connect: connection refused)
```

Depends on https://github.com/projectdiscovery/goflags/pull/55

2022-06-09 13:19 UTC, ehsandeep requested changes
Not sure if it's existing bug or new bug but config file location is not same if running with `sudo`

```console
$ ./naabu -hc
Version: 2.0.7
Operative System: darwin
Architecture: arm64
Privileged/NET_RAW: Ko
Config file "/Users/geekboy/.config/naabu/config.yaml" Read => Ok
Config file "/Users/geekboy/.config/naabu/config.yaml" Write => Ok
IPv4 connectivity to scanme.sh:80 => Ko (dial tcp4 128.199.158.128:80: connect: connection refused)
IPv6 connectivity to scanme.sh:80 => Ko (dial tcp6 [2400:6180:0:d0::91:1001]:80: connect: connection refused)
```

```console
$ sudo echo $HOME
/Users/geekboy
```


```console
$ sudo ./naabu -hc
Version: 2.0.7
Operative System: darwin
Architecture: arm64
Privileged/NET_RAW: Ok
Config file "/var/root/.config/naabu/config.yaml" Read => Ko (open /var/root/.config/naabu/config.yaml: no such file or directory)
Config file "/var/root/.config/naabu/config.yaml" Write => Ko (open /var/root/.config/naabu/config.yaml: no such file or directory)
IPv4 connectivity to scanme.sh:80 => Ko (dial tcp4 128.199.158.128:80: connect: connection refused)
IPv6 connectivity to scanme.sh:80 => Ko (dial tcp6 [2400:6180:0:d0::91:1001]:80: connect: connection refused)
```

2022-06-09 13:23 UTC, ehsandeep submitted a review, later dismissed
See above.

2022-06-09 14:24 UTC, Ice3man543 approved these changes

2022-06-10 07:25 UTC, ehsandeep approved these changes

2022-06-10 07:25 UTC, merged