move waitgroup add out of goroutines to fix the occasional panic
projectdiscovery/naabu pull request #382
Opened 2022-07-06 04:57 UTC by parrasajad

2022-07-06 09:33 UTC, Mzack9999 requested changes
I left some comments to review, please see if they make sense

2022-07-06 09:33 UTC, Mzack9999 commented on v2/pkg/runner/runner.go
>  					go func(ip string, port int) {
I think that the original go routine is redundant itself (probably leftover of some refactor), and we can unwrap it directly as follows:
```go
go func(ip string, port int) {
    if shouldUseRawPackets {
        r.RawSocketEnumeration(ip, port)
    } else {
        r.wgscan.Add()
        go r.handleHostPort(ip, port)
    }
}(ip, port)
```
To:
```go
if shouldUseRawPackets {
    r.RawSocketEnumeration(ip, port)
} else {
    r.wgscan.Add()
    go r.handleHostPort(ip, port)
}
```

2022-07-06 09:33 UTC, Mzack9999 commented on v2/pkg/runner/runner.go
>  				go func(port int) {
same as above

2022-07-08 15:33 UTC, ehsandeep approved these changes

2022-07-08 15:34 UTC, merged