add port threshold
projectdiscovery/naabu pull request #416
Opened 2022-08-22 13:15 UTC by parrasajad

2022-08-23 13:20 UTC, Mzack9999 requested changes

2022-08-23 13:20 UTC, Mzack9999 commented on v2/pkg/runner/options.go
> +		flagSet.IntVarP(&options.PortThreshold, "pts", "port-threshold", 0, "port threshold to skip port scan for the host"),
I think we can add validation in `Options.validateOptions: the threshold should be between 0 and 65535.

2022-08-24 19:05 UTC, Mzack9999 approved these changes
```console
$ go run . -pts 5 -host scanme.sh
...
[INF] Found 4 ports on host scanme.sh (128.199.158.128)
scanme.sh:80
scanme.sh:444
scanme.sh:22
scanme.sh:443
$ go run . -pts 3 -host scanme.sh -verbose
...
root privileges
[DBG] Skipping 128.199.158.128, Threshold reached
```

2022-08-24 19:16 UTC, ehsandeep requested changes
On Mac, found results are not displayed:

```console
go run . -pts 5 -host scanme.sh -v

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v2.1.0

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
[DBG] Using host 128.199.158.128 for enumeration
[INF] Running CONNECT scan with non root privileges
[DBG] Skipping 128.199.158.128, Threshold reached 
```

2022-08-24 19:18 UTC, ehsandeep commented
also with SYN scan, `-pts` is not working:

```console
sudo go run . -pts 2 -host scanme.sh -silent

scanme.sh:444
scanme.sh:22
scanme.sh:25
scanme.sh:80
scanme.sh:443
scanme.sh:445
```

2022-08-25 08:44 UTC, Mzack9999 commented
- [ ] Please update `REAME.MD`

2022-08-25 09:29 UTC, ehsandeep approved these changes

2022-08-25 10:41 UTC, Mzack9999 approved these changes

2022-08-25 10:52 UTC, merged