Fix Replace freeport with pd fork #471
projectdiscovery/naabu pull request #478
Opened 2022-11-16 22:23 UTC by foxcores

Fix issue #471

2022-11-16 23:18 UTC, Mzack9999 requested changes

2022-11-16 23:18 UTC, Mzack9999 commented on v2/pkg/scan/scan.go
>  					gologger.Debug().Msgf("Discarding TCP packet from %s:%d not matching %s:%d port\n", addr.String(), tcp.DstPort, dstIP, rawPort)
`rawPort` is now a struct => `rawPort.Port`

2022-11-16 23:18 UTC, Mzack9999 commented on v2/pkg/scan/scan.go
> +	rawPort, err := freeport.GetFreePort("0.0.0.0", freeport.TCP)
We can use the following shortcut:
```go
rawPort, err := freeport.GetFreeTCPPort("")
```
empty address will attempt to listen on all interfaces (equivalent to `0.0.0.0`)

2022-11-16 23:18 UTC, Mzack9999 commented on v2/pkg/scan/scan_unix.go
> +	rawPort, err := freeport.GetFreePort("0.0.0.0", freeport.TCP)
same as above

2022-11-17 22:19 UTC, Mzack9999 approved these changes

2022-11-18 12:26 UTC, ehsandeep approved these changes

2022-11-18 12:26 UTC, merged