fix printing issue with hostname in passive mode
projectdiscovery/naabu pull request #788
Opened 2023-09-04 12:21 UTC by dogancanbakir

Closes #787.

before:
```console
$ go run . -host projectdiscovery.io -ec -silent -passive

104.26.7.152:2087
104.26.7.152:8443
104.26.7.152:8880
104.26.7.152:80
104.26.7.152:443
104.26.7.152:2082
104.26.7.152:2083
```

after:
```console
$ go run . -host projectdiscovery.io -ec -silent -passive
projectdiscovery.io:443
projectdiscovery.io:2052
projectdiscovery.io:2082
projectdiscovery.io:2083
projectdiscovery.io:2087
projectdiscovery.io:2095
projectdiscovery.io:8443
projectdiscovery.io:80
```

2023-09-05 20:13 UTC, ehsandeep requested changes
We can add test with `-passive` option.

2023-09-06 19:13 UTC, Mzack9999 approved these changes

2023-09-06 19:13 UTC, Mzack9999 commented on v2/pkg/runner/targets.go
> +func joinHostPort(host, port string) string {
I think this is worth moving to `utils` with `TryJoinHostPort` or something similar, what do you think?

2023-09-07 08:36 UTC, dogancanbakir commented on v2/pkg/runner/targets.go
> +func joinHostPort(host, port string) string {
Implemented in utils pkg https://github.com/projectdiscovery/utils/pull/255

2023-09-22 07:57 UTC, ehsandeep approved these changes

2023-09-22 07:57 UTC, merged